import Head from 'next/head'
import Header from '../components/Header'
import "tailwindcss/tailwind.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>查公車</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </Head>
      <Header />
    </div>
  );
}
